"""E4 traceable draft knowledge

Revision ID: 0004_knowledge_draft
Revises: 0003_text_segments
Create Date: 2026-09-27 17:49:03.513612
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0004_knowledge_draft'
down_revision = '0003_text_segments'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('concept_type', sa.String(length=60), nullable=False),
    sa.Column('era', sa.String(length=120), nullable=True),
    sa.Column('school', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_concept_public_id'),
    schema='knowledge'
    )
    op.create_table('formula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_formula_public_id'),
    schema='knowledge'
    )
    op.create_table('herb',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('era', sa.String(length=120), nullable=True),
    sa.Column('school', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_herb_public_id'),
    schema='knowledge'
    )
    op.create_table('concept_term',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=300), nullable=False),
    sa.Column('term_kind', sa.String(length=30), nullable=False),
    sa.Column('era', sa.String(length=120), nullable=True),
    sa.Column('school', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['knowledge.concept.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'term', 'term_kind', name='uq_concept_term'),
    schema='knowledge'
    )
    op.create_index('ix_concept_term_text', 'concept_term', ['term'], unique=False, schema='knowledge')
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_evidence_public_id'),
    schema='knowledge'
    )
    op.create_table('formula_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formula_id', sa.UUID(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('era', sa.String(length=120), nullable=True),
    sa.Column('school', sa.String(length=120), nullable=True),
    sa.Column('indications', sa.Text(), nullable=True),
    sa.Column('effects', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('preparation', sa.Text(), nullable=True),
    sa.Column('cautions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['knowledge.formula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formula_id', 'revision_no', name='uq_formula_revision_no'),
    schema='knowledge'
    )
    op.create_table('herb_term',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('herb_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=300), nullable=False),
    sa.Column('term_kind', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['knowledge.herb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('herb_id', 'term', 'term_kind', name='uq_herb_term'),
    schema='knowledge'
    )
    op.create_table('relation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('subject_concept_id', sa.UUID(), nullable=False),
    sa.Column('object_concept_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=80), nullable=False),
    sa.Column('assertion_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_concept_id'], ['knowledge.concept.id'], ),
    sa.ForeignKeyConstraint(['subject_concept_id'], ['knowledge.concept.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_relation_public_id'),
    schema='knowledge'
    )
    op.create_table('formula_ingredient',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formula_revision_id', sa.UUID(), nullable=False),
    sa.Column('herb_id', sa.UUID(), nullable=True),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('amount_original', sa.String(length=120), nullable=True),
    sa.Column('amount_normalized', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('dose_ratio', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('processing', sa.String(length=300), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formula_revision_id'], ['knowledge.formula_revision.id'], ),
    sa.ForeignKeyConstraint(['herb_id'], ['knowledge.herb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formula_revision_id', 'sequence_no', name='uq_formula_ingredient_sequence'),
    schema='knowledge'
    )
    op.create_table('entity_mention',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_revision_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('surface_text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['knowledge.concept.id'], ),
    sa.ForeignKeyConstraint(['segment_revision_id'], ['source.text_segment_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index('ix_mention_segment', 'entity_mention', ['segment_revision_id'], unique=False, schema='knowledge')
    op.create_table('evidence_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('source_revision_id', sa.UUID(), nullable=False),
    sa.Column('anchor_segment_revision_id', sa.UUID(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=False),
    sa.Column('context_after', sa.Text(), nullable=False),
    sa.Column('citation_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_class', sa.String(length=40), nullable=False),
    sa.Column('evidence_strength', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quote_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anchor_segment_revision_id'], ['source.text_segment_revision.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['knowledge.evidence.id'], ),
    sa.ForeignKeyConstraint(['source_revision_id'], ['source.source_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'revision_no', name='uq_evidence_revision_no'),
    schema='knowledge'
    )
    op.create_index('ix_evidence_revision_source', 'evidence_revision', ['source_revision_id', 'status'], unique=False, schema='knowledge')
    op.create_table('herb_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('herb_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['herb_id'], ['knowledge.herb.id'], ),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('herb_id', 'evidence_revision_id', name='uq_herb_evidence'),
    schema='knowledge'
    )
    op.create_table('concept_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['knowledge.concept.id'], ),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'evidence_revision_id', name='uq_concept_evidence'),
    schema='knowledge'
    )
    op.create_table('evidence_segment_ref',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.Column('segment_revision_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['segment_revision_id'], ['source.text_segment_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_revision_id', 'segment_revision_id', name='uq_evidence_ref_segment'),
    sa.UniqueConstraint('evidence_revision_id', 'sequence_no', name='uq_evidence_ref_sequence'),
    schema='knowledge'
    )
    op.create_table('formula_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('formula_revision_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['formula_revision_id'], ['knowledge.formula_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formula_revision_id', 'evidence_revision_id', name='uq_formula_evidence'),
    schema='knowledge'
    )
    op.create_table('relation_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['knowledge.relation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relation_id', 'evidence_revision_id', name='uq_relation_evidence'),
    schema='knowledge'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_evidence', schema='knowledge')
    op.drop_table('formula_evidence', schema='knowledge')
    op.drop_table('evidence_segment_ref', schema='knowledge')
    op.drop_table('concept_evidence', schema='knowledge')
    op.drop_table('herb_evidence', schema='knowledge')
    op.drop_index('ix_evidence_revision_source', table_name='evidence_revision', schema='knowledge')
    op.drop_table('evidence_revision', schema='knowledge')
    op.drop_index('ix_mention_segment', table_name='entity_mention', schema='knowledge')
    op.drop_table('entity_mention', schema='knowledge')
    op.drop_table('formula_ingredient', schema='knowledge')
    op.drop_table('relation', schema='knowledge')
    op.drop_table('herb_term', schema='knowledge')
    op.drop_table('formula_revision', schema='knowledge')
    op.drop_table('evidence', schema='knowledge')
    op.drop_index('ix_concept_term_text', table_name='concept_term', schema='knowledge')
    op.drop_table('concept_term', schema='knowledge')
    op.drop_table('herb', schema='knowledge')
    op.drop_table('formula', schema='knowledge')
    op.drop_table('concept', schema='knowledge')
    # ### end Alembic commands ###
