"""E5 knowledge review and publish barrier

Revision ID: 0005_knowledge_publish
Revises: 0004_knowledge_draft
Create Date: 2026-09-27 17:58:56.862884
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0005_knowledge_publish'
down_revision = '0004_knowledge_draft'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index('ix_human_review_target', 'human_review', ['target_kind', 'target_id'], unique=False, schema='governance')
    op.create_table('knowledge_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_knowledge_version_public_id'),
    sa.UniqueConstraint('version_no', name='uq_knowledge_version_no'),
    schema='governance'
    )
    op.create_table('quality_issue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('target_kind', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index('ix_quality_issue_open', 'quality_issue', ['status', 'severity', 'target_kind', 'target_id'], unique=False, schema='governance')
    op.create_table('index_build',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fts_status', sa.String(length=30), nullable=False),
    sa.Column('vector_status', sa.String(length=30), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['governance.knowledge_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index('ix_index_build_version', 'index_build', ['knowledge_version_id', 'status'], unique=False, schema='governance')
    op.create_table('knowledge_runtime_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_knowledge_version_id', sa.UUID(), nullable=True),
    sa.Column('active_index_build_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(active_knowledge_version_id IS NULL) = (active_index_build_id IS NULL)', name='ck_knowledge_runtime_pointer_pair'),
    sa.CheckConstraint('id = 1', name='ck_knowledge_runtime_singleton'),
    sa.ForeignKeyConstraint(['active_index_build_id'], ['governance.index_build.id'], ),
    sa.ForeignKeyConstraint(['active_knowledge_version_id'], ['governance.knowledge_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_table('knowledge_version_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=True),
    sa.Column('formula_revision_id', sa.UUID(), nullable=True),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('relation_id', sa.UUID(), nullable=True),
    sa.Column('herb_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('num_nonnulls(evidence_revision_id, formula_revision_id, concept_id, relation_id, herb_id) = 1', name='ck_knowledge_item_one_object'),
    sa.ForeignKeyConstraint(['concept_id'], ['knowledge.concept.id'], ),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['formula_revision_id'], ['knowledge.formula_revision.id'], ),
    sa.ForeignKeyConstraint(['herb_id'], ['knowledge.herb.id'], ),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['governance.knowledge_version.id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['knowledge.relation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_version_id', 'concept_id', name='uq_kv_concept'),
    sa.UniqueConstraint('knowledge_version_id', 'evidence_revision_id', name='uq_kv_evidence'),
    sa.UniqueConstraint('knowledge_version_id', 'formula_revision_id', name='uq_kv_formula'),
    sa.UniqueConstraint('knowledge_version_id', 'herb_id', name='uq_kv_herb'),
    sa.UniqueConstraint('knowledge_version_id', 'relation_id', name='uq_kv_relation'),
    schema='governance'
    )
    op.execute("INSERT INTO governance.knowledge_runtime_state (id, updated_at) VALUES (1, now())")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_version_item', schema='governance')
    op.drop_table('knowledge_runtime_state', schema='governance')
    op.drop_index('ix_index_build_version', table_name='index_build', schema='governance')
    op.drop_table('index_build', schema='governance')
    op.drop_index('ix_quality_issue_open', table_name='quality_issue', schema='governance')
    op.drop_table('quality_issue', schema='governance')
    op.drop_table('knowledge_version', schema='governance')
    op.drop_index('ix_human_review_target', table_name='human_review', schema='governance')
    op.drop_table('human_review', schema='governance')
    # ### end Alembic commands ###
