"""E6 retrieval chunks and vector records

Revision ID: 0006_retrieval
Revises: 0005_knowledge_publish
Create Date: 2026-09-27 18:08:15.539804
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import tcm_platform.vector_type

revision = '0006_retrieval'
down_revision = '0005_knowledge_publish'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_build_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.Column('source_revision_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', token_text)", persisted=True), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['index_build_id'], ['governance.index_build.id'], ),
    sa.ForeignKeyConstraint(['source_revision_id'], ['source.source_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_build_id', 'evidence_revision_id', name='uq_chunk_build_evidence'),
    schema='knowledge'
    )
    op.create_index('ix_chunk_build', 'retrieval_chunk', ['index_build_id'], unique=False, schema='knowledge')
    op.create_index('ix_chunk_fts', 'retrieval_chunk', ['search_vector'], unique=False, schema='knowledge', postgresql_using='gin')
    op.create_index('ix_chunk_trgm', 'retrieval_chunk', ['chunk_text'], unique=False, schema='knowledge', postgresql_using='gin', postgresql_ops={'chunk_text': 'gin_trgm_ops'})
    op.create_table('embedding_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_build_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', tcm_platform.vector_type.Vector(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge.retrieval_chunk.id'], ),
    sa.ForeignKeyConstraint(['index_build_id'], ['governance.index_build.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_embedding_chunk'),
    schema='knowledge'
    )
    op.create_index('ix_embedding_build', 'embedding_record', ['index_build_id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embedding_build', table_name='embedding_record', schema='knowledge')
    op.drop_table('embedding_record', schema='knowledge')
    op.drop_index('ix_chunk_trgm', table_name='retrieval_chunk', schema='knowledge', postgresql_using='gin', postgresql_ops={'chunk_text': 'gin_trgm_ops'})
    op.drop_index('ix_chunk_fts', table_name='retrieval_chunk', schema='knowledge', postgresql_using='gin')
    op.drop_index('ix_chunk_build', table_name='retrieval_chunk', schema='knowledge')
    op.drop_table('retrieval_chunk', schema='knowledge')
    # ### end Alembic commands ###
