"""E7 research task and claim pool

Revision ID: 0008_research_task
Revises: 0007_retrieval_benchmark
Create Date: 2026-09-27 18:36:07.022457
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0008_research_task'
down_revision = '0007_retrieval_benchmark'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=80), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('draft_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_research_task_public_id'),
    schema='research'
    )
    op.create_index('ix_research_task_status', 'research_task', ['status', 'created_at'], unique=False, schema='research')
    op.create_table('agent_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visible_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'role', 'round_no', name='uq_agent_run_round'),
    schema='research'
    )
    op.create_table('sub_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'sequence_no', name='uq_sub_question_order'),
    schema='research'
    )
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('parent_claim_id', sa.UUID(), nullable=True),
    sa.Column('agent_role', sa.String(length=50), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('assertion_text', sa.Text(), nullable=False),
    sa.Column('rationale_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['research.agent_run.id'], ),
    sa.ForeignKeyConstraint(['parent_claim_id'], ['research.claim.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_claim_task_role', 'claim', ['task_id', 'agent_role'], unique=False, schema='research')
    op.create_table('evidence_retrieval_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_retrieval_event_task', 'evidence_retrieval_event', ['task_id', 'created_at'], unique=False, schema='research')
    op.create_table('task_evidence_ref',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('evidence_revision_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_revision_id'], ['knowledge.evidence_revision.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'evidence_revision_id', name='uq_task_evidence_member'),
    schema='research'
    )
    op.create_table('claim_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('task_evidence_ref_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['research.claim.id'], ),
    sa.ForeignKeyConstraint(['task_evidence_ref_id'], ['research.task_evidence_ref.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'task_evidence_ref_id', name='uq_claim_evidence'),
    schema='research'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_evidence', schema='research')
    op.drop_table('task_evidence_ref', schema='research')
    op.drop_index('ix_retrieval_event_task', table_name='evidence_retrieval_event', schema='research')
    op.drop_table('evidence_retrieval_event', schema='research')
    op.drop_index('ix_claim_task_role', table_name='claim', schema='research')
    op.drop_table('claim', schema='research')
    op.drop_table('sub_question', schema='research')
    op.drop_table('agent_run', schema='research')
    op.drop_index('ix_research_task_status', table_name='research_task', schema='research')
    op.drop_table('research_task', schema='research')
    # ### end Alembic commands ###
