"""record cloud model invocations

Revision ID: 0009_model_invocation
Revises: 0008_research_task
Create Date: 2026-09-27 19:03:25.626078
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0009_model_invocation'
down_revision = '0008_research_task'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_invocation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_class', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['research.agent_run.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_model_invocation_task', 'model_invocation', ['task_id', 'created_at'], unique=False, schema='research')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_invocation_task', table_name='model_invocation', schema='research')
    op.drop_table('model_invocation', schema='research')
    # ### end Alembic commands ###
