"""add research pause and cancel control

Revision ID: 0010_research_control
Revises: 0009_model_invocation
Create Date: 2026-09-27 19:15:02.912988
"""

import sqlalchemy as sa
from alembic import op

revision = '0010_research_control'
down_revision = '0009_model_invocation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_task', sa.Column('control_state', sa.String(length=30),
                                          server_default='ACTIVE', nullable=False),
                  schema='research')
    op.alter_column('research_task', 'control_state', server_default=None,
                    schema='research')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_task', 'control_state', schema='research')
    # ### end Alembic commands ###
