"""add critique evidence request and rebuttal

Revision ID: 0012_debate
Revises: 0011_audit_result
Create Date: 2026-09-27 20:37:54.294564
"""

import sqlalchemy as sa
from alembic import op

revision = '0012_debate'
down_revision = '0011_audit_result'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critique',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('target_claim_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('rationale_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['research.agent_run.id'], ),
    sa.ForeignKeyConstraint(['target_claim_id'], ['research.claim.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_critique_task_claim', 'critique', ['task_id', 'target_claim_id'], unique=False, schema='research')
    op.create_table('evidence_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('critique_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['critique_id'], ['research.critique.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='research'
    )
    op.create_index('ix_evidence_request_task_status', 'evidence_request', ['task_id', 'status'], unique=False, schema='research')
    op.create_table('rebuttal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('critique_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('rationale_summary', sa.Text(), nullable=False),
    sa.Column('revised_claim_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(action = 'REVISE' AND revised_claim_id IS NOT NULL) OR (action <> 'REVISE' AND revised_claim_id IS NULL)"),
    sa.ForeignKeyConstraint(['agent_run_id'], ['research.agent_run.id'], ),
    sa.ForeignKeyConstraint(['critique_id'], ['research.critique.id'], ),
    sa.ForeignKeyConstraint(['revised_claim_id'], ['research.claim.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['research.research_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('critique_id', 'round_no', name='uq_rebuttal_critique_round'),
    schema='research'
    )
    op.add_column('evidence_retrieval_event', sa.Column('evidence_request_id', sa.UUID(), nullable=True), schema='research')
    op.create_foreign_key('fk_retrieval_event_request', 'evidence_retrieval_event', 'evidence_request', ['evidence_request_id'], ['id'], source_schema='research', referent_schema='research')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_retrieval_event_request', 'evidence_retrieval_event', schema='research', type_='foreignkey')
    op.drop_column('evidence_retrieval_event', 'evidence_request_id', schema='research')
    op.drop_table('rebuttal', schema='research')
    op.drop_index('ix_evidence_request_task_status', table_name='evidence_request', schema='research')
    op.drop_table('evidence_request', schema='research')
    op.drop_index('ix_critique_task_claim', table_name='critique', schema='research')
    op.drop_table('critique', schema='research')
    # ### end Alembic commands ###
